// <auto-generated />
using Application.Core.Infraestructure.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Application.Core.Infraestructure.Persistance.Migrations
{
    [DbContext(typeof(LoginDefaultDbContext))]
    [Migration("20250926171406_MigracionInicial")]
    partial class MigracionInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Application.Core.Domain.Entities.Modulo", b =>
                {
                    b.Property<int>("IdModulo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdModulo"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Icono")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdModulo");

                    b.ToTable("Cat_Modulos", (string)null);
                });

            modelBuilder.Entity("Application.Core.Domain.Entities.Opcion", b =>
                {
                    b.Property<int>("IdOpcion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOpcion"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Icono")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("IdModulo")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.HasKey("IdOpcion")
                        .HasName("PK_Cat_OpcionesModulo");

                    b.HasIndex(new[] { "IdModulo" }, "IX_Cat_OpcionesModulo_IdModulo");

                    b.ToTable("Cat_Opciones", (string)null);
                });

            modelBuilder.Entity("Application.Core.Domain.Entities.OpcionRol", b =>
                {
                    b.Property<int>("IdOpcionRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOpcionRol"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("IdOpcion")
                        .HasColumnType("int");

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.HasKey("IdOpcionRol")
                        .HasName("PK_OpcionesRol");

                    b.HasIndex("IdOpcion");

                    b.HasIndex(new[] { "IdRol" }, "IX_OpcionesRol_IdRol");

                    b.ToTable("Cat_OpcionesRol", (string)null);
                });

            modelBuilder.Entity("Application.Core.Domain.Entities.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdRol");

                    b.ToTable("Cat_Roles", (string)null);
                });

            modelBuilder.Entity("Application.Core.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuarioLlave")
                        .HasColumnType("int");

                    b.HasKey("IdUsuario")
                        .HasName("PK__Usuario__5B65BF97E14C2783");

                    b.HasIndex(new[] { "IdRol" }, "IX_Usuario_Rol");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("Application.Core.Domain.Entities.Opcion", b =>
                {
                    b.HasOne("Application.Core.Domain.Entities.Modulo", "IdModuloNavigation")
                        .WithMany("CatOpciones")
                        .HasForeignKey("IdModulo")
                        .IsRequired()
                        .HasConstraintName("FK_Cat_Opciones_Cat_Modulos");

                    b.Navigation("IdModuloNavigation");
                });

            modelBuilder.Entity("Application.Core.Domain.Entities.OpcionRol", b =>
                {
                    b.HasOne("Application.Core.Domain.Entities.Opcion", "IdOpcionNavigation")
                        .WithMany("CatOpcionesRols")
                        .HasForeignKey("IdOpcion")
                        .IsRequired()
                        .HasConstraintName("FK_Cat_OpcionesRol_Cat_Opciones");

                    b.HasOne("Application.Core.Domain.Entities.Rol", "IdRolNavigation")
                        .WithMany("CatOpcionesRols")
                        .HasForeignKey("IdRol")
                        .IsRequired()
                        .HasConstraintName("FK_Cat_OpcionesRol_Cat_Roles");

                    b.Navigation("IdOpcionNavigation");

                    b.Navigation("IdRolNavigation");
                });

            modelBuilder.Entity("Application.Core.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("Application.Core.Domain.Entities.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .IsRequired()
                        .HasConstraintName("FK_Usuario_Cat_Roles");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Application.Core.Domain.Entities.Modulo", b =>
                {
                    b.Navigation("CatOpciones");
                });

            modelBuilder.Entity("Application.Core.Domain.Entities.Opcion", b =>
                {
                    b.Navigation("CatOpcionesRols");
                });

            modelBuilder.Entity("Application.Core.Domain.Entities.Rol", b =>
                {
                    b.Navigation("CatOpcionesRols");

                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
